version: '3'
services:

  blockchain:
    build: .
    command: /go/bin/csd start --rpc.laddr tcp://0.0.0.0:26657
    ports:
      - 26657:26657

  goat1:
    build: .
    command: ./scripts/startRESTserver.sh
    container_name: goat1
    depends_on:
      - blockchain
    ports:
      - 1317:1317

  herd:
    image: nginx:latest
    container_name: herd
    depends_on:
      - goat1
    volumes:
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
