version: '3'
services:

  blockchain:
    build: .
    command: ./docker-run.sh
    volumes:
      - ./backup:/backup
      - ./docker-run.sh:/home/tendermint/docker-run.sh
      - ./peer_nodes.json:/home/tendermint/peer_nodes.json
      - ./files/:/home/tendermint/files/
    ports:
      - 26657:26657
      - 26658:26658
      - 1317:1317
      - 9090:9090
      - 9091:9091
      - 4500:4500

  goat:
    build: ./goat/
    ports:
      - 31337:31337

  herd:
    image: nginx:latest
    container_name: herd
    volumes:
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/dhparam-4096.pem:/etc/nginx/ssl/dhparam-4096.pem
      - ./files/:/files/
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    depends_on: 
      - blockchain
      - goat
