version: '3'
services:

  blockchain:
    build: .
    command: ./docker-run.sh
    volumes:
       - blockchain-data:/var/blockchain
    ports:
      - 26657:26657

  goat:
    build: .
    command: ./scripts/startRESTserver.sh
    container_name: goat
    depends_on:
      - blockchain
    ports:
      - 1317:1317

  herd:
    image: nginx:latest
    container_name: herd
    depends_on:
      - goat
    volumes:
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/dhparam-4096.pem:/etc/nginx/ssl/dhparam-4096.pem
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
