version: '3'
services:

  blockchain:
    build: .
    command: ./docker-run.sh
    volumes:
       - ./blockchain-data/:/var/blockchain/
    ports:
      - 26659:26659
      - 1318:1318

  herd:
    image: nginx:latest
    container_name: herd
    depends_on:
      - goat
      - hottub
    volumes:
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/fullchain.pem
      - /etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem:/etc/letsencrypt/live/cardchain.crowdcontrol.network/privkey.pem
      - /etc/letsencrypt/live/hottub.crowdcontrol.network/fullchain.pem:/etc/letsencrypt/live/hottub.crowdcontrol.network/fullchain.pem
      - /etc/letsencrypt/live/hottub.crowdcontrol.network/privkey.pem:/etc/letsencrypt/live/hottub.crowdcontrol.network/privkey.pem
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/dhparam-4096.pem:/etc/nginx/ssl/dhparam-4096.pem
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
