version: '3'
services:

  blockchain:
    build: .
    command: ./docker-run.sh
    volumes:
      - ./backup:/backup
      - ./docker-run.sh:/home/tendermint/docker-run.sh
      - ./peer_nodes.json:/home/tendermint/peer_nodes.json
    ports:
      - 26657:26657
      - 26658:26658
      - 1317:1317
      - 9090:9090
      - 9091:9091
      - 4500:4500
