#!/usr/bin/env bash

# Ingite wrapper to ensure ignite version compatibility
# Takes optional `--path <path>` option to specify an ingite installation at a different location then the default one
# All other arguments are passed on to ignite

IGNITE_VERSION="v0.26.2"


if [[ $1 == "--path" ]]; then
    path=$2

    if ! [ -f $path ]; then
        echo "[Wrapper] Path '$path' was not found"
        exit 1
    fi

    args=${@:3}
else
    path=$(which ignite)
    if [[ $? != 0 ]]; then
        echo "[Wrapper] Error: No ignite binary found"
        exit 1
    fi
    args=$@
fi

version=$($path version | grep -E "Ignite CLI version:" | awk '{print $NF}')
if [[ $version != $IGNITE_VERSION ]]; then
    echo "[Wrapper] Error: No matching ignite version found, required is $IGNITE_VERSION but $version was found"
    exit 1
fi

echo "[Wrapper] Using $path $IGNITE_VERSION"

$path $args
