#!/usr/bin/env bash
if [ $# -lt 1 ]; then
  echo 1>&2 "Please specify set id via argument"
  exit 2
fi

#technology
Cardchaind tx cardchain add-card-to-set $1	71 --from jannik
Cardchaind tx cardchain add-card-to-set $1	44 --from jannik
Cardchaind tx cardchain add-card-to-set $1	142 --from jannik
Cardchaind tx cardchain add-card-to-set $1	143 --from jannik
Cardchaind tx cardchain add-card-to-set $1	252 --from jannik
Cardchaind tx cardchain add-card-to-set $1	45 --from jannik
Cardchaind tx cardchain add-card-to-set $1 25 --from jannik
Cardchaind tx cardchain add-card-to-set $1	27 --from jannik
Cardchaind tx cardchain add-card-to-set $1	51 --from jannik
Cardchaind tx cardchain add-card-to-set $1	54 --from jannik
Cardchaind tx cardchain add-card-to-set $1	225 --from jannik
Cardchaind tx cardchain add-card-to-set $1	140 --from jannik
Cardchaind tx cardchain add-card-to-set $1	46 --from jannik
Cardchaind tx cardchain add-card-to-set $1	53 --from jannik
Cardchaind tx cardchain add-card-to-set $1	55 --from jannik
Cardchaind tx cardchain add-card-to-set $1	56 --from jannik
Cardchaind tx cardchain add-card-to-set $1	67 --from jannik
Cardchaind tx cardchain add-card-to-set $1	85 --from jannik
Cardchaind tx cardchain add-card-to-set $1 299 --from jannik
Cardchaind tx cardchain add-card-to-set $1 167 --from jannik
Cardchaind tx cardchain add-card-to-set $1 191 --from jannik
Cardchaind tx cardchain add-card-to-set $1	52 --from jannik
Cardchaind tx cardchain add-card-to-set $1	247 --from jannik
Cardchaind tx cardchain add-card-to-set $1	43 --from jannik
Cardchaind tx cardchain add-card-to-set $1	62 --from jannik
Cardchaind tx cardchain add-card-to-set $1	284 --from jannik
Cardchaind tx cardchain add-card-to-set $1	59 --from jannik
Cardchaind tx cardchain add-card-to-set $1	139 --from jannik
Cardchaind tx cardchain add-card-to-set $1	253 --from jannik
Cardchaind tx cardchain add-card-to-set $1	381 --from jannik
Cardchaind tx cardchain add-card-to-set $1 412 --from jannik
#nature
Cardchaind tx cardchain add-card-to-set $1	407 --from jannik
Cardchaind tx cardchain add-card-to-set $1	73 --from jannik
Cardchaind tx cardchain add-card-to-set $1	411 --from jannik
Cardchaind tx cardchain add-card-to-set $1	154 --from jannik
Cardchaind tx cardchain add-card-to-set $1	147 --from jannik
Cardchaind tx cardchain add-card-to-set $1	156 --from jannik
Cardchaind tx cardchain add-card-to-set $1	0 --from jannik
Cardchaind tx cardchain add-card-to-set $1	155 --from jannik
Cardchaind tx cardchain add-card-to-set $1 122 --from jannik
Cardchaind tx cardchain add-card-to-set $1	464 --from jannik
Cardchaind tx cardchain add-card-to-set $1	77 --from jannik
Cardchaind tx cardchain add-card-to-set $1	246 --from jannik
Cardchaind tx cardchain add-card-to-set $1	119 --from jannik
Cardchaind tx cardchain add-card-to-set $1	75 --from jannik
Cardchaind tx cardchain add-card-to-set $1	149 --from jannik
Cardchaind tx cardchain add-card-to-set $1	112 --from jannik
Cardchaind tx cardchain add-card-to-set $1	380 --from jannik
Cardchaind tx cardchain add-card-to-set $1 227 --from jannik
Cardchaind tx cardchain add-card-to-set $1	63 --from jannik
Cardchaind tx cardchain add-card-to-set $1	64 --from jannik
Cardchaind tx cardchain add-card-to-set $1 21 --from jannik
Cardchaind tx cardchain add-card-to-set $1 254 --from jannik
Cardchaind tx cardchain add-card-to-set $1 108 --from jannik
Cardchaind tx cardchain add-card-to-set $1 74 --from jannik
Cardchaind tx cardchain add-card-to-set $1 28 --from jannik
Cardchaind tx cardchain add-card-to-set $1 125 --from jannik
Cardchaind tx cardchain add-card-to-set $1	397 --from jannik
Cardchaind tx cardchain add-card-to-set $1	159 --from jannik
Cardchaind tx cardchain add-card-to-set $1	410 --from jannik
Cardchaind tx cardchain add-card-to-set $1	158 --from jannik
#mysticism
Cardchaind tx cardchain add-card-to-set $1	47 --from jannik
Cardchaind tx cardchain add-card-to-set $1	36 --from jannik
Cardchaind tx cardchain add-card-to-set $1	65 --from jannik
Cardchaind tx cardchain add-card-to-set $1	95 --from jannik
Cardchaind tx cardchain add-card-to-set $1	100 --from jannik
Cardchaind tx cardchain add-card-to-set $1	17 --from jannik
Cardchaind tx cardchain add-card-to-set $1	23 --from jannik
Cardchaind tx cardchain add-card-to-set $1 216 --from jannik
Cardchaind tx cardchain add-card-to-set $1 101 --from jannik
Cardchaind tx cardchain add-card-to-set $1 103 --from jannik
Cardchaind tx cardchain add-card-to-set $1 18 --from jannik
Cardchaind tx cardchain add-card-to-set $1	223 --from jannik
Cardchaind tx cardchain add-card-to-set $1	12 --from jannik
Cardchaind tx cardchain add-card-to-set $1	222 --from jannik
Cardchaind tx cardchain add-card-to-set $1	232 --from jannik
Cardchaind tx cardchain add-card-to-set $1	97 --from jannik
Cardchaind tx cardchain add-card-to-set $1	33 --from jannik
Cardchaind tx cardchain add-card-to-set $1 98 --from jannik
Cardchaind tx cardchain add-card-to-set $1	150 --from jannik
Cardchaind tx cardchain add-card-to-set $1	66 --from jannik
Cardchaind tx cardchain add-card-to-set $1	42 --from jannik
Cardchaind tx cardchain add-card-to-set $1 114 --from jannik
Cardchaind tx cardchain add-card-to-set $1 151 --from jannik
Cardchaind tx cardchain add-card-to-set $1 168 --from jannik
Cardchaind tx cardchain add-card-to-set $1 135 --from jannik
Cardchaind tx cardchain add-card-to-set $1 99 --from jannik
Cardchaind tx cardchain add-card-to-set $1	24 --from jannik
Cardchaind tx cardchain add-card-to-set $1	102 --from jannik
Cardchaind tx cardchain add-card-to-set $1	104 --from jannik
Cardchaind tx cardchain add-card-to-set $1	224 --from jannik
#culture
Cardchaind tx cardchain add-card-to-set $1	255 --from jannik
Cardchaind tx cardchain add-card-to-set $1	41 --from jannik
Cardchaind tx cardchain add-card-to-set $1	8 --from jannik
Cardchaind tx cardchain add-card-to-set $1	84 --from jannik
Cardchaind tx cardchain add-card-to-set $1	83 --from jannik
Cardchaind tx cardchain add-card-to-set $1	15 --from jannik
Cardchaind tx cardchain add-card-to-set $1	256 --from jannik
Cardchaind tx cardchain add-card-to-set $1	107 --from jannik
Cardchaind tx cardchain add-card-to-set $1	50 --from jannik
Cardchaind tx cardchain add-card-to-set $1	170 --from jannik
Cardchaind tx cardchain add-card-to-set $1	109 --from jannik
Cardchaind tx cardchain add-card-to-set $1	105 --from jannik
Cardchaind tx cardchain add-card-to-set $1 372 --from jannik
Cardchaind tx cardchain add-card-to-set $1 9 --from jannik
Cardchaind tx cardchain add-card-to-set $1	10 --from jannik
Cardchaind tx cardchain add-card-to-set $1 49 --from jannik
Cardchaind tx cardchain add-card-to-set $1	110 --from jannik
Cardchaind tx cardchain add-card-to-set $1	248 --from jannik
Cardchaind tx cardchain add-card-to-set $1	38 --from jannik
Cardchaind tx cardchain add-card-to-set $1	86 --from jannik
Cardchaind tx cardchain add-card-to-set $1	19 --from jannik
Cardchaind tx cardchain add-card-to-set $1 14 --from jannik
Cardchaind tx cardchain add-card-to-set $1 123 --from jannik
Cardchaind tx cardchain add-card-to-set $1	31 --from jannik
Cardchaind tx cardchain add-card-to-set $1	20 --from jannik
Cardchaind tx cardchain add-card-to-set $1 141 --from jannik
Cardchaind tx cardchain add-card-to-set $1	257 --from jannik
Cardchaind tx cardchain add-card-to-set $1	16 --from jannik
Cardchaind tx cardchain add-card-to-set $1	138 --from jannik
# multi class
Cardchaind tx cardchain add-card-to-set $1	562 --from jannik
Cardchaind tx cardchain add-card-to-set $1	189 --from jannik
Cardchaind tx cardchain add-card-to-set $1	152 --from jannik
Cardchaind tx cardchain add-card-to-set $1	126 --from jannik
Cardchaind tx cardchain add-card-to-set $1	514 --from jannik
Cardchaind tx cardchain add-card-to-set $1	379 --from jannik
Cardchaind tx cardchain add-card-to-set $1	238 --from jannik
Cardchaind tx cardchain add-card-to-set $1	128 --from jannik
Cardchaind tx cardchain add-card-to-set $1	118 --from jannik
Cardchaind tx cardchain add-card-to-set $1	13 --from jannik
Cardchaind tx cardchain add-card-to-set $1	132 --from jannik
Cardchaind tx cardchain add-card-to-set $1	87 --from jannik
Cardchaind tx cardchain add-card-to-set $1	29 --from jannik
Cardchaind tx cardchain add-card-to-set $1	1 --from jannik
Cardchaind tx cardchain add-card-to-set $1	397 --from jannik
Cardchaind tx cardchain add-card-to-set $1	131 --from jannik
Cardchaind tx cardchain add-card-to-set $1	129 --from jannik
Cardchaind tx cardchain add-card-to-set $1	120 --from jannik
Cardchaind tx cardchain add-card-to-set $1	507 --from jannik
Cardchaind tx cardchain add-card-to-set $1	215 --from jannik
Cardchaind tx cardchain add-card-to-set $1	124 --from jannik
Cardchaind tx cardchain add-card-to-set $1	115 --from jannik