#!/usr/bin/env bash
if [ $# -lt 1 ]; then
  echo 1>&2 "Please specify set id via argument"
  exit 2
fi

Cardchaind tx cardchain set-card-rarity	71 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	44 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	142 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	143 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	252 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	45 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	25 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	27 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	51 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	54 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	225 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	140 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	46 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	53 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	55 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	56 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	67 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	85 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	299 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	167 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	191 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	52 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	247 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	43 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	62 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	284 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	59 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	139 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	253 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	381 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	412 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	407 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	73 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	411 $1 common --from jannik		SHIT
Cardchaind tx cardchain set-card-rarity	154 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	147 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	156 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	0 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	155 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	122 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	464 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	77 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	246 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	119 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	75 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	149 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	112 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	380 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	227 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	63 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	64 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	21 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	254 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	108 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	74 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	28 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	125 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	397 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	159 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	410 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	158 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	47 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	36 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	65 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	95 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	100 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	17 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	23 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	216 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	101 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	103 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	18 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	223 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	12 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	222 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	232 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	97 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	33 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	98 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	150 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	66 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	42 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	114 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	151 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	168 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	135 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	99 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	24 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	102 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	104 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	224 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	255 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	41 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	8 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	84 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	83 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	15 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	256 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	107 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	50 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	170 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	109 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	105 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	372 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	9 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	10 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	49 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	110 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	248 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	38 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	86 $1 uncommon --from jannik
Cardchaind tx cardchain set-card-rarity	19 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	14 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	123 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	31 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	20 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	141 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	257 $1 common --from jannik
Cardchaind tx cardchain set-card-rarity	16 $1 rare --from jannik
Cardchaind tx cardchain set-card-rarity	138 $1 uncommon --from jannik