"use strict";
// Generated by Ignite ignite.com/cli
Object.defineProperty(exports, "__esModule", { value: true });
exports.queryClient = exports.txClient = exports.registry = exports.MsgCancelUpgrade = exports.MsgSoftwareUpgrade = void 0;
const stargate_1 = require("@cosmjs/stargate");
const proto_signing_1 = require("@cosmjs/proto-signing");
const registry_1 = require("./registry");
const rest_1 = require("./rest");
const tx_1 = require("./types/cosmos/upgrade/v1beta1/tx");
Object.defineProperty(exports, "MsgSoftwareUpgrade", { enumerable: true, get: function () { return tx_1.MsgSoftwareUpgrade; } });
const tx_2 = require("./types/cosmos/upgrade/v1beta1/tx");
Object.defineProperty(exports, "MsgCancelUpgrade", { enumerable: true, get: function () { return tx_2.MsgCancelUpgrade; } });
exports.registry = new proto_signing_1.Registry(registry_1.msgTypes);
const defaultFee = {
    amount: [],
    gas: "200000",
};
const txClient = ({ signer, prefix, addr } = { addr: "http://localhost:26657", prefix: "cosmos" }) => {
    return {
        async sendMsgSoftwareUpgrade({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgSoftwareUpgrade: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await stargate_1.SigningStargateClient.connectWithSigner(addr, signer, { registry: exports.registry, prefix });
                let msg = this.msgSoftwareUpgrade({ value: tx_1.MsgSoftwareUpgrade.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgSoftwareUpgrade: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgCancelUpgrade({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgCancelUpgrade: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await stargate_1.SigningStargateClient.connectWithSigner(addr, signer, { registry: exports.registry, prefix });
                let msg = this.msgCancelUpgrade({ value: tx_2.MsgCancelUpgrade.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgCancelUpgrade: Could not broadcast Tx: ' + e.message);
            }
        },
        msgSoftwareUpgrade({ value }) {
            try {
                return { typeUrl: "/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade", value: tx_1.MsgSoftwareUpgrade.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgSoftwareUpgrade: Could not create message: ' + e.message);
            }
        },
        msgCancelUpgrade({ value }) {
            try {
                return { typeUrl: "/cosmos.upgrade.v1beta1.MsgCancelUpgrade", value: tx_2.MsgCancelUpgrade.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgCancelUpgrade: Could not create message: ' + e.message);
            }
        },
    };
};
exports.txClient = txClient;
const queryClient = ({ addr: addr } = { addr: "http://localhost:1317" }) => {
    return new rest_1.Api({ baseURL: addr });
};
exports.queryClient = queryClient;
class SDKModule {
    constructor(client) {
        this.registry = [];
        this.query = (0, exports.queryClient)({ addr: client.env.apiURL });
        this.updateTX(client);
        client.on('signer-changed', (signer) => {
            this.updateTX(client);
        });
    }
    updateTX(client) {
        const methods = (0, exports.txClient)({
            signer: client.signer,
            addr: client.env.rpcURL,
            prefix: client.env.prefix ?? "cosmos",
        });
        this.tx = methods;
        for (let m in methods) {
            this.tx[m] = methods[m].bind(this.tx);
        }
    }
}
;
const Module = (test) => {
    return {
        module: {
            CosmosUpgradeV1Beta1: new SDKModule(test)
        },
        registry: registry_1.msgTypes
    };
};
exports.default = Module;
