"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventRevoke = exports.EventGrant = exports.GrantQueueItem = exports.GrantAuthorization = exports.Grant = exports.GenericAuthorization = void 0;
const authz_1 = require("./types/cosmos/authz/v1beta1/authz");
Object.defineProperty(exports, "GenericAuthorization", { enumerable: true, get: function () { return authz_1.GenericAuthorization; } });
const authz_2 = require("./types/cosmos/authz/v1beta1/authz");
Object.defineProperty(exports, "Grant", { enumerable: true, get: function () { return authz_2.Grant; } });
const authz_3 = require("./types/cosmos/authz/v1beta1/authz");
Object.defineProperty(exports, "GrantAuthorization", { enumerable: true, get: function () { return authz_3.GrantAuthorization; } });
const authz_4 = require("./types/cosmos/authz/v1beta1/authz");
Object.defineProperty(exports, "GrantQueueItem", { enumerable: true, get: function () { return authz_4.GrantQueueItem; } });
const event_1 = require("./types/cosmos/authz/v1beta1/event");
Object.defineProperty(exports, "EventGrant", { enumerable: true, get: function () { return event_1.EventGrant; } });
const event_2 = require("./types/cosmos/authz/v1beta1/event");
Object.defineProperty(exports, "EventRevoke", { enumerable: true, get: function () { return event_2.EventRevoke; } });
