"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TallyParams = exports.VotingParams = exports.DepositParams = exports.Vote = exports.TallyResult = exports.Proposal = exports.Deposit = exports.TextProposal = exports.WeightedVoteOption = void 0;
const gov_1 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "WeightedVoteOption", { enumerable: true, get: function () { return gov_1.WeightedVoteOption; } });
const gov_2 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "TextProposal", { enumerable: true, get: function () { return gov_2.TextProposal; } });
const gov_3 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "Deposit", { enumerable: true, get: function () { return gov_3.Deposit; } });
const gov_4 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "Proposal", { enumerable: true, get: function () { return gov_4.Proposal; } });
const gov_5 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "TallyResult", { enumerable: true, get: function () { return gov_5.TallyResult; } });
const gov_6 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "Vote", { enumerable: true, get: function () { return gov_6.Vote; } });
const gov_7 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "DepositParams", { enumerable: true, get: function () { return gov_7.DepositParams; } });
const gov_8 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "VotingParams", { enumerable: true, get: function () { return gov_8.VotingParams; } });
const gov_9 = require("./types/cosmos/gov/v1beta1/gov");
Object.defineProperty(exports, "TallyParams", { enumerable: true, get: function () { return gov_9.TallyParams; } });
