package types

import (
	cdctypes "github.com/cosmos/cosmos-sdk/codec/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/cosmos/cosmos-sdk/types/msgservice"
	// this line is used by starport scaffolding # 1
)

func RegisterInterfaces(registrar cdctypes.InterfaceRegistry) {
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEncounterEdit{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgUserCreate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardSchemeBuy{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardSaveContent{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardVote{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardTransfer{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardDonate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardArtworkAdd{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardArtistChange{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilRegister{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilDeregister{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgMatchReport{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilCreate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgMatchReporterAppoint{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetCreate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetCardAdd{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetCardRemove{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetContributorAdd{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetContributorRemove{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetFinalize{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetArtworkAdd{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetStoryAdd{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgBoosterPackBuy{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSellOfferCreate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSellOfferBuy{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSellOfferRemove{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardRaritySet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilResponseCommit{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilResponseReveal{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCouncilRestart{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgMatchConfirm{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgProfileCardSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgProfileWebsiteSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgProfileBioSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgBoosterPackOpen{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgBoosterPackTransfer{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetStoryWriterSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetArtistSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardVoteMulti{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgMatchOpen{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetNameSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgProfileAliasSet{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEarlyAccessInvite{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgZealyConnect{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEncounterCreate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEncounterDo{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEncounterClose{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEarlyAccessDisinvite{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardBan{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgEarlyAccessGrant{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgSetActivate{},
	)
	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgCardCopyrightClaim{},
	)
	// this line is used by starport scaffolding # 3

	registrar.RegisterImplementations((*sdk.Msg)(nil),
		&MsgUpdateParams{},
	)
	msgservice.RegisterMsgServiceDesc(registrar, &_Msg_serviceDesc)
}
