// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cardchain/cardchain/running_average.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RunningAverage struct {
	Arr []int64 `protobuf:"varint,1,rep,packed,name=arr,proto3" json:"arr,omitempty"`
}

func (m *RunningAverage) Reset()         { *m = RunningAverage{} }
func (m *RunningAverage) String() string { return proto.CompactTextString(m) }
func (*RunningAverage) ProtoMessage()    {}
func (*RunningAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a520f579564035a6, []int{0}
}
func (m *RunningAverage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RunningAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RunningAverage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RunningAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunningAverage.Merge(m, src)
}
func (m *RunningAverage) XXX_Size() int {
	return m.Size()
}
func (m *RunningAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_RunningAverage.DiscardUnknown(m)
}

var xxx_messageInfo_RunningAverage proto.InternalMessageInfo

func (m *RunningAverage) GetArr() []int64 {
	if m != nil {
		return m.Arr
	}
	return nil
}

func init() {
	proto.RegisterType((*RunningAverage)(nil), "cardchain.cardchain.RunningAverage")
}

func init() {
	proto.RegisterFile("cardchain/cardchain/running_average.proto", fileDescriptor_a520f579564035a6)
}

var fileDescriptor_a520f579564035a6 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0x4e, 0x2c, 0x4a,
	0x49, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x47, 0xb0, 0x8a, 0x4a, 0xf3, 0xf2, 0x32, 0xf3, 0xd2, 0xe3,
	0x13, 0xcb, 0x52, 0x8b, 0x12, 0xd3, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0xe1,
	0x0a, 0xf4, 0xe0, 0x2c, 0x25, 0x25, 0x2e, 0xbe, 0x20, 0x88, 0x6a, 0x47, 0x88, 0x62, 0x21, 0x01,
	0x2e, 0xe6, 0xc4, 0xa2, 0x22, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xe6, 0x20, 0x10, 0xd3, 0x29, 0xe8,
	0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e,
	0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x2c, 0xd2, 0x33, 0x4b, 0x32, 0x4a,
	0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x5d, 0x52, 0x93, 0x53, 0xf3, 0x4a, 0x8a, 0x12, 0x73, 0x9c,
	0x13, 0x8b, 0x52, 0xdc, 0x13, 0x73, 0x53, 0x91, 0x1c, 0x54, 0x81, 0xc4, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0x4e, 0x62, 0x03, 0xbb, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x90, 0xa5, 0xa6,
	0xc0, 0x00, 0x00, 0x00,
}

func (m *RunningAverage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RunningAverage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RunningAverage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Arr) > 0 {
		dAtA2 := make([]byte, len(m.Arr)*10)
		var j1 int
		for _, num1 := range m.Arr {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintRunningAverage(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRunningAverage(dAtA []byte, offset int, v uint64) int {
	offset -= sovRunningAverage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RunningAverage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Arr) > 0 {
		l = 0
		for _, e := range m.Arr {
			l += sovRunningAverage(uint64(e))
		}
		n += 1 + sovRunningAverage(uint64(l)) + l
	}
	return n
}

func sovRunningAverage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRunningAverage(x uint64) (n int) {
	return sovRunningAverage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RunningAverage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRunningAverage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RunningAverage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RunningAverage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRunningAverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Arr = append(m.Arr, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRunningAverage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthRunningAverage
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthRunningAverage
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Arr) == 0 {
					m.Arr = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRunningAverage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Arr = append(m.Arr, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Arr", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRunningAverage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRunningAverage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRunningAverage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRunningAverage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRunningAverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRunningAverage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRunningAverage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRunningAverage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRunningAverage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRunningAverage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRunningAverage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRunningAverage = fmt.Errorf("proto: unexpected end of group")
)
