// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cardchain/cardchain/user.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CouncilStatus int32

const (
	CouncilStatus_available      CouncilStatus = 0
	CouncilStatus_unavailable    CouncilStatus = 1
	CouncilStatus_openCouncil    CouncilStatus = 2
	CouncilStatus_startedCouncil CouncilStatus = 3
)

var CouncilStatus_name = map[int32]string{
	0: "available",
	1: "unavailable",
	2: "openCouncil",
	3: "startedCouncil",
}

var CouncilStatus_value = map[string]int32{
	"available":      0,
	"unavailable":    1,
	"openCouncil":    2,
	"startedCouncil": 3,
}

func (x CouncilStatus) String() string {
	return proto.EnumName(CouncilStatus_name, int32(x))
}

func (CouncilStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{0}
}

type AirDrop int32

const (
	AirDrop_play   AirDrop = 0
	AirDrop_vote   AirDrop = 1
	AirDrop_create AirDrop = 2
	AirDrop_buy    AirDrop = 3
	AirDrop_user   AirDrop = 4
)

var AirDrop_name = map[int32]string{
	0: "play",
	1: "vote",
	2: "create",
	3: "buy",
	4: "user",
}

var AirDrop_value = map[string]int32{
	"play":   0,
	"vote":   1,
	"create": 2,
	"buy":    3,
	"user":   4,
}

func (x AirDrop) String() string {
	return proto.EnumName(AirDrop_name, int32(x))
}

func (AirDrop) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{1}
}

type User struct {
	Alias                string                `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	OwnedCardSchemes     []uint64              `protobuf:"varint,2,rep,packed,name=ownedCardSchemes,proto3" json:"ownedCardSchemes,omitempty"`
	OwnedPrototypes      []uint64              `protobuf:"varint,3,rep,packed,name=ownedPrototypes,proto3" json:"ownedPrototypes,omitempty"`
	Cards                []uint64              `protobuf:"varint,4,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	VoteRights           []*VoteRight          `protobuf:"bytes,5,rep,name=voteRights,proto3" json:"voteRights,omitempty"`
	CouncilParticipation *CouncilParticipation `protobuf:"bytes,6,opt,name=councilParticipation,proto3" json:"councilParticipation,omitempty"`
	ReportMatches        bool                  `protobuf:"varint,7,opt,name=ReportMatches,proto3" json:"ReportMatches,omitempty"`
	ProfileCard          uint64                `protobuf:"varint,8,opt,name=profileCard,proto3" json:"profileCard,omitempty"`
	AirDrops             *AirDrops             `protobuf:"bytes,9,opt,name=airDrops,proto3" json:"airDrops,omitempty"`
	BoosterPacks         []*BoosterPack        `protobuf:"bytes,10,rep,name=boosterPacks,proto3" json:"boosterPacks,omitempty"`
	Website              string                `protobuf:"bytes,11,opt,name=website,proto3" json:"website,omitempty"`
	Biography            string                `protobuf:"bytes,12,opt,name=biography,proto3" json:"biography,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_User.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return m.Size()
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *User) GetOwnedCardSchemes() []uint64 {
	if m != nil {
		return m.OwnedCardSchemes
	}
	return nil
}

func (m *User) GetOwnedPrototypes() []uint64 {
	if m != nil {
		return m.OwnedPrototypes
	}
	return nil
}

func (m *User) GetCards() []uint64 {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *User) GetVoteRights() []*VoteRight {
	if m != nil {
		return m.VoteRights
	}
	return nil
}

func (m *User) GetCouncilParticipation() *CouncilParticipation {
	if m != nil {
		return m.CouncilParticipation
	}
	return nil
}

func (m *User) GetReportMatches() bool {
	if m != nil {
		return m.ReportMatches
	}
	return false
}

func (m *User) GetProfileCard() uint64 {
	if m != nil {
		return m.ProfileCard
	}
	return 0
}

func (m *User) GetAirDrops() *AirDrops {
	if m != nil {
		return m.AirDrops
	}
	return nil
}

func (m *User) GetBoosterPacks() []*BoosterPack {
	if m != nil {
		return m.BoosterPacks
	}
	return nil
}

func (m *User) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *User) GetBiography() string {
	if m != nil {
		return m.Biography
	}
	return ""
}

type CouncilParticipation struct {
	Status  CouncilStatus `protobuf:"varint,1,opt,name=status,proto3,enum=DecentralCardGame.cardchain.cardchain.CouncilStatus" json:"status,omitempty"`
	Council uint64        `protobuf:"varint,2,opt,name=council,proto3" json:"council,omitempty"`
}

func (m *CouncilParticipation) Reset()         { *m = CouncilParticipation{} }
func (m *CouncilParticipation) String() string { return proto.CompactTextString(m) }
func (*CouncilParticipation) ProtoMessage()    {}
func (*CouncilParticipation) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{1}
}
func (m *CouncilParticipation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CouncilParticipation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CouncilParticipation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CouncilParticipation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CouncilParticipation.Merge(m, src)
}
func (m *CouncilParticipation) XXX_Size() int {
	return m.Size()
}
func (m *CouncilParticipation) XXX_DiscardUnknown() {
	xxx_messageInfo_CouncilParticipation.DiscardUnknown(m)
}

var xxx_messageInfo_CouncilParticipation proto.InternalMessageInfo

func (m *CouncilParticipation) GetStatus() CouncilStatus {
	if m != nil {
		return m.Status
	}
	return CouncilStatus_available
}

func (m *CouncilParticipation) GetCouncil() uint64 {
	if m != nil {
		return m.Council
	}
	return 0
}

type BoosterPack struct {
	SetId     uint64 `protobuf:"varint,1,opt,name=setId,proto3" json:"setId,omitempty"`
	TimeStamp int64  `protobuf:"varint,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	// How often the different rarities will appear in a BoosterPack
	RaritiesPerPack []uint64 `protobuf:"varint,3,rep,packed,name=raritiesPerPack,proto3" json:"raritiesPerPack,omitempty"`
	// The chances of the rare beeing a normal rare, an exceptional or a unique
	DropRatiosPerPack []uint64 `protobuf:"varint,4,rep,packed,name=dropRatiosPerPack,proto3" json:"dropRatiosPerPack,omitempty"`
}

func (m *BoosterPack) Reset()         { *m = BoosterPack{} }
func (m *BoosterPack) String() string { return proto.CompactTextString(m) }
func (*BoosterPack) ProtoMessage()    {}
func (*BoosterPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{2}
}
func (m *BoosterPack) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BoosterPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BoosterPack.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BoosterPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoosterPack.Merge(m, src)
}
func (m *BoosterPack) XXX_Size() int {
	return m.Size()
}
func (m *BoosterPack) XXX_DiscardUnknown() {
	xxx_messageInfo_BoosterPack.DiscardUnknown(m)
}

var xxx_messageInfo_BoosterPack proto.InternalMessageInfo

func (m *BoosterPack) GetSetId() uint64 {
	if m != nil {
		return m.SetId
	}
	return 0
}

func (m *BoosterPack) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *BoosterPack) GetRaritiesPerPack() []uint64 {
	if m != nil {
		return m.RaritiesPerPack
	}
	return nil
}

func (m *BoosterPack) GetDropRatiosPerPack() []uint64 {
	if m != nil {
		return m.DropRatiosPerPack
	}
	return nil
}

type AirDrops struct {
	Vote   bool `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	Create bool `protobuf:"varint,2,opt,name=create,proto3" json:"create,omitempty"`
	Buy    bool `protobuf:"varint,3,opt,name=buy,proto3" json:"buy,omitempty"`
	Play   bool `protobuf:"varint,4,opt,name=play,proto3" json:"play,omitempty"`
	User   bool `protobuf:"varint,5,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *AirDrops) Reset()         { *m = AirDrops{} }
func (m *AirDrops) String() string { return proto.CompactTextString(m) }
func (*AirDrops) ProtoMessage()    {}
func (*AirDrops) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb1a13ac65ffc756, []int{3}
}
func (m *AirDrops) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AirDrops) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AirDrops.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AirDrops) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AirDrops.Merge(m, src)
}
func (m *AirDrops) XXX_Size() int {
	return m.Size()
}
func (m *AirDrops) XXX_DiscardUnknown() {
	xxx_messageInfo_AirDrops.DiscardUnknown(m)
}

var xxx_messageInfo_AirDrops proto.InternalMessageInfo

func (m *AirDrops) GetVote() bool {
	if m != nil {
		return m.Vote
	}
	return false
}

func (m *AirDrops) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

func (m *AirDrops) GetBuy() bool {
	if m != nil {
		return m.Buy
	}
	return false
}

func (m *AirDrops) GetPlay() bool {
	if m != nil {
		return m.Play
	}
	return false
}

func (m *AirDrops) GetUser() bool {
	if m != nil {
		return m.User
	}
	return false
}

func init() {
	proto.RegisterEnum("DecentralCardGame.cardchain.cardchain.CouncilStatus", CouncilStatus_name, CouncilStatus_value)
	proto.RegisterEnum("DecentralCardGame.cardchain.cardchain.AirDrop", AirDrop_name, AirDrop_value)
	proto.RegisterType((*User)(nil), "DecentralCardGame.cardchain.cardchain.User")
	proto.RegisterType((*CouncilParticipation)(nil), "DecentralCardGame.cardchain.cardchain.CouncilParticipation")
	proto.RegisterType((*BoosterPack)(nil), "DecentralCardGame.cardchain.cardchain.BoosterPack")
	proto.RegisterType((*AirDrops)(nil), "DecentralCardGame.cardchain.cardchain.AirDrops")
}

func init() { proto.RegisterFile("cardchain/cardchain/user.proto", fileDescriptor_eb1a13ac65ffc756) }

var fileDescriptor_eb1a13ac65ffc756 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xce, 0x66, 0xb7, 0xc9, 0x66, 0xd2, 0x9f, 0xc5, 0xaa, 0x90, 0x85, 0xd0, 0x6a, 0x15, 0x81,
	0xb4, 0xaa, 0x50, 0x82, 0x02, 0x07, 0x24, 0xb8, 0xd0, 0x56, 0x42, 0x08, 0x90, 0x22, 0x17, 0x7a,
	0xe0, 0xe6, 0xdd, 0x98, 0xc4, 0x62, 0xb3, 0x5e, 0xd9, 0x4e, 0x4b, 0x2e, 0x3c, 0x03, 0x57, 0xde,
	0x88, 0x63, 0x8f, 0x1c, 0x51, 0xfb, 0x02, 0x3c, 0x02, 0xb2, 0x37, 0x9b, 0xa4, 0x4d, 0x0e, 0xe1,
	0x36, 0xf3, 0xd9, 0xf3, 0xf9, 0x9b, 0xf1, 0xa7, 0x81, 0x30, 0xa5, 0x72, 0x98, 0x8e, 0x29, 0xcf,
	0x7b, 0xcb, 0x68, 0xaa, 0x98, 0xec, 0x16, 0x52, 0x68, 0x81, 0x1e, 0x9f, 0xb2, 0x94, 0xe5, 0x5a,
	0xd2, 0xec, 0x84, 0xca, 0xe1, 0x1b, 0x3a, 0x61, 0xdd, 0xc5, 0xbd, 0x65, 0xf4, 0x20, 0xda, 0x44,
	0x73, 0x21, 0x34, 0xcf, 0x47, 0x25, 0x51, 0xe7, 0xaf, 0x07, 0xde, 0x27, 0xc5, 0x24, 0x3a, 0x84,
	0x1d, 0x9a, 0x71, 0xaa, 0xb0, 0x13, 0x39, 0x71, 0x8b, 0x94, 0x09, 0x3a, 0x82, 0x40, 0x5c, 0xe6,
	0x6c, 0x68, 0x5e, 0x39, 0x4b, 0xc7, 0x6c, 0xc2, 0x14, 0xae, 0x47, 0x6e, 0xec, 0x91, 0x35, 0x1c,
	0xc5, 0x70, 0x60, 0xb1, 0x81, 0x21, 0xd6, 0xb3, 0x82, 0x29, 0xec, 0xda, 0xab, 0x77, 0x61, 0xf3,
	0x96, 0x91, 0xa3, 0xb0, 0x67, 0xcf, 0xcb, 0x04, 0x0d, 0x00, 0x2e, 0x84, 0x66, 0x84, 0x8f, 0xc6,
	0x5a, 0xe1, 0x9d, 0xc8, 0x8d, 0xdb, 0xfd, 0xa7, 0xdd, 0xad, 0x1a, 0xed, 0x9e, 0x57, 0x85, 0x64,
	0x85, 0x03, 0x09, 0x38, 0x4c, 0xc5, 0x34, 0x4f, 0x79, 0x36, 0xa0, 0x52, 0xf3, 0x94, 0x17, 0x54,
	0x73, 0x91, 0xe3, 0x46, 0xe4, 0xc4, 0xed, 0xfe, 0xcb, 0x2d, 0xb9, 0x4f, 0x36, 0x50, 0x90, 0x8d,
	0xc4, 0xe8, 0x11, 0xec, 0x11, 0x56, 0x08, 0xa9, 0x3f, 0x50, 0x9d, 0x8e, 0x99, 0xc2, 0xcd, 0xc8,
	0x89, 0x7d, 0x72, 0x1b, 0x44, 0x11, 0xb4, 0x0b, 0x29, 0xbe, 0xf0, 0x8c, 0x99, 0x77, 0xb1, 0x1f,
	0x39, 0xb1, 0x47, 0x56, 0x21, 0xf4, 0x0e, 0x7c, 0xca, 0xe5, 0xa9, 0x14, 0x85, 0xc2, 0x2d, 0x2b,
	0xb6, 0xb7, 0xa5, 0xd8, 0xd7, 0xf3, 0x32, 0xb2, 0x20, 0x40, 0xe7, 0xb0, 0x9b, 0x08, 0xa1, 0x34,
	0x93, 0x03, 0x9a, 0x7e, 0x55, 0x18, 0xec, 0x64, 0xfb, 0x5b, 0x12, 0x1e, 0x2f, 0x4b, 0xc9, 0x2d,
	0x1e, 0x84, 0xa1, 0x79, 0xc9, 0x12, 0xc5, 0x35, 0xc3, 0x6d, 0xeb, 0x99, 0x2a, 0x45, 0x0f, 0xa1,
	0x95, 0x70, 0x31, 0x92, 0xb4, 0x18, 0xcf, 0xf0, 0xae, 0x3d, 0x5b, 0x02, 0x9d, 0xef, 0x70, 0xb8,
	0x69, 0xa4, 0xe8, 0x3d, 0x34, 0x94, 0xa6, 0x7a, 0x5a, 0x5a, 0x70, 0xbf, 0xff, 0xfc, 0xff, 0xfe,
	0xe7, 0xcc, 0xd6, 0x92, 0x39, 0x87, 0x51, 0x37, 0xff, 0x22, 0x5c, 0xb7, 0x03, 0xae, 0xd2, 0xce,
	0x4f, 0x07, 0xda, 0x2b, 0x5d, 0x19, 0x37, 0x2a, 0xa6, 0xdf, 0x0e, 0xed, 0xb3, 0x1e, 0x29, 0x13,
	0xd3, 0x83, 0xe6, 0x13, 0x76, 0xa6, 0xe9, 0xa4, 0xb0, 0x0c, 0x2e, 0x59, 0x02, 0xc6, 0xeb, 0x92,
	0x4a, 0xae, 0x39, 0x53, 0x83, 0x92, 0xa6, 0xf2, 0xfa, 0x1d, 0x18, 0x3d, 0x81, 0x7b, 0x43, 0x29,
	0x0a, 0x62, 0x7a, 0x5c, 0xdc, 0x2d, 0x7d, 0xbf, 0x7e, 0xd0, 0x29, 0xc0, 0xaf, 0x7e, 0x10, 0x21,
	0xf0, 0x8c, 0x97, 0xad, 0x2c, 0x9f, 0xd8, 0x18, 0xdd, 0x87, 0x46, 0x2a, 0x19, 0xd5, 0xcc, 0x4a,
	0xf2, 0xc9, 0x3c, 0x43, 0x01, 0xb8, 0xc9, 0x74, 0x86, 0x5d, 0x0b, 0x9a, 0xd0, 0x54, 0x17, 0x19,
	0x9d, 0x61, 0xaf, 0xac, 0x36, 0xb1, 0xc1, 0xcc, 0x0e, 0xc1, 0x3b, 0x25, 0x66, 0xe2, 0xa3, 0x8f,
	0xb0, 0x77, 0x6b, 0x80, 0x68, 0x0f, 0x5a, 0xf4, 0x82, 0xf2, 0x8c, 0x26, 0x19, 0x0b, 0x6a, 0xe8,
	0x00, 0xda, 0xd3, 0x7c, 0x09, 0x38, 0x06, 0x10, 0x05, 0xcb, 0xe7, 0x45, 0x41, 0x1d, 0x21, 0xd8,
	0x57, 0x9a, 0x4a, 0xcd, 0x86, 0x15, 0xe6, 0x1e, 0xbd, 0x82, 0xe6, 0xbc, 0x0f, 0xe4, 0x97, 0x42,
	0x82, 0x9a, 0x89, 0x4c, 0x13, 0x81, 0x83, 0xa0, 0x6a, 0x23, 0xa8, 0xa3, 0xa6, 0x95, 0x1e, 0xb8,
	0xe6, 0xd8, 0x28, 0x0a, 0xbc, 0x63, 0xf2, 0xeb, 0x3a, 0x74, 0xae, 0xae, 0x43, 0xe7, 0xcf, 0x75,
	0xe8, 0xfc, 0xb8, 0x09, 0x6b, 0x57, 0x37, 0x61, 0xed, 0xf7, 0x4d, 0x58, 0xfb, 0xfc, 0x62, 0xc4,
	0xf5, 0x78, 0x9a, 0x74, 0x53, 0x31, 0xe9, 0xad, 0xb9, 0xa3, 0x77, 0xb2, 0xd8, 0x71, 0xdf, 0x56,
	0xf6, 0x9d, 0xdd, 0x39, 0x49, 0xc3, 0xee, 0xbb, 0x67, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0x0d, 0xb4, 0x7b, 0x5a, 0x05, 0x00, 0x00,
}

func (m *User) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *User) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *User) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Biography) > 0 {
		i -= len(m.Biography)
		copy(dAtA[i:], m.Biography)
		i = encodeVarintUser(dAtA, i, uint64(len(m.Biography)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.Website) > 0 {
		i -= len(m.Website)
		copy(dAtA[i:], m.Website)
		i = encodeVarintUser(dAtA, i, uint64(len(m.Website)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.BoosterPacks) > 0 {
		for iNdEx := len(m.BoosterPacks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BoosterPacks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUser(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.AirDrops != nil {
		{
			size, err := m.AirDrops.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUser(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.ProfileCard != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.ProfileCard))
		i--
		dAtA[i] = 0x40
	}
	if m.ReportMatches {
		i--
		if m.ReportMatches {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.CouncilParticipation != nil {
		{
			size, err := m.CouncilParticipation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUser(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.VoteRights) > 0 {
		for iNdEx := len(m.VoteRights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VoteRights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUser(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Cards) > 0 {
		dAtA4 := make([]byte, len(m.Cards)*10)
		var j3 int
		for _, num := range m.Cards {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintUser(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0x22
	}
	if len(m.OwnedPrototypes) > 0 {
		dAtA6 := make([]byte, len(m.OwnedPrototypes)*10)
		var j5 int
		for _, num := range m.OwnedPrototypes {
			for num >= 1<<7 {
				dAtA6[j5] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j5++
			}
			dAtA6[j5] = uint8(num)
			j5++
		}
		i -= j5
		copy(dAtA[i:], dAtA6[:j5])
		i = encodeVarintUser(dAtA, i, uint64(j5))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OwnedCardSchemes) > 0 {
		dAtA8 := make([]byte, len(m.OwnedCardSchemes)*10)
		var j7 int
		for _, num := range m.OwnedCardSchemes {
			for num >= 1<<7 {
				dAtA8[j7] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j7++
			}
			dAtA8[j7] = uint8(num)
			j7++
		}
		i -= j7
		copy(dAtA[i:], dAtA8[:j7])
		i = encodeVarintUser(dAtA, i, uint64(j7))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Alias) > 0 {
		i -= len(m.Alias)
		copy(dAtA[i:], m.Alias)
		i = encodeVarintUser(dAtA, i, uint64(len(m.Alias)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CouncilParticipation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CouncilParticipation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CouncilParticipation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Council != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.Council))
		i--
		dAtA[i] = 0x10
	}
	if m.Status != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BoosterPack) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BoosterPack) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BoosterPack) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DropRatiosPerPack) > 0 {
		dAtA10 := make([]byte, len(m.DropRatiosPerPack)*10)
		var j9 int
		for _, num := range m.DropRatiosPerPack {
			for num >= 1<<7 {
				dAtA10[j9] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j9++
			}
			dAtA10[j9] = uint8(num)
			j9++
		}
		i -= j9
		copy(dAtA[i:], dAtA10[:j9])
		i = encodeVarintUser(dAtA, i, uint64(j9))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RaritiesPerPack) > 0 {
		dAtA12 := make([]byte, len(m.RaritiesPerPack)*10)
		var j11 int
		for _, num := range m.RaritiesPerPack {
			for num >= 1<<7 {
				dAtA12[j11] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j11++
			}
			dAtA12[j11] = uint8(num)
			j11++
		}
		i -= j11
		copy(dAtA[i:], dAtA12[:j11])
		i = encodeVarintUser(dAtA, i, uint64(j11))
		i--
		dAtA[i] = 0x1a
	}
	if m.TimeStamp != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.TimeStamp))
		i--
		dAtA[i] = 0x10
	}
	if m.SetId != 0 {
		i = encodeVarintUser(dAtA, i, uint64(m.SetId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AirDrops) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AirDrops) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AirDrops) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.User {
		i--
		if m.User {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Play {
		i--
		if m.Play {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Buy {
		i--
		if m.Buy {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Create {
		i--
		if m.Create {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Vote {
		i--
		if m.Vote {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUser(dAtA []byte, offset int, v uint64) int {
	offset -= sovUser(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *User) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Alias)
	if l > 0 {
		n += 1 + l + sovUser(uint64(l))
	}
	if len(m.OwnedCardSchemes) > 0 {
		l = 0
		for _, e := range m.OwnedCardSchemes {
			l += sovUser(uint64(e))
		}
		n += 1 + sovUser(uint64(l)) + l
	}
	if len(m.OwnedPrototypes) > 0 {
		l = 0
		for _, e := range m.OwnedPrototypes {
			l += sovUser(uint64(e))
		}
		n += 1 + sovUser(uint64(l)) + l
	}
	if len(m.Cards) > 0 {
		l = 0
		for _, e := range m.Cards {
			l += sovUser(uint64(e))
		}
		n += 1 + sovUser(uint64(l)) + l
	}
	if len(m.VoteRights) > 0 {
		for _, e := range m.VoteRights {
			l = e.Size()
			n += 1 + l + sovUser(uint64(l))
		}
	}
	if m.CouncilParticipation != nil {
		l = m.CouncilParticipation.Size()
		n += 1 + l + sovUser(uint64(l))
	}
	if m.ReportMatches {
		n += 2
	}
	if m.ProfileCard != 0 {
		n += 1 + sovUser(uint64(m.ProfileCard))
	}
	if m.AirDrops != nil {
		l = m.AirDrops.Size()
		n += 1 + l + sovUser(uint64(l))
	}
	if len(m.BoosterPacks) > 0 {
		for _, e := range m.BoosterPacks {
			l = e.Size()
			n += 1 + l + sovUser(uint64(l))
		}
	}
	l = len(m.Website)
	if l > 0 {
		n += 1 + l + sovUser(uint64(l))
	}
	l = len(m.Biography)
	if l > 0 {
		n += 1 + l + sovUser(uint64(l))
	}
	return n
}

func (m *CouncilParticipation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovUser(uint64(m.Status))
	}
	if m.Council != 0 {
		n += 1 + sovUser(uint64(m.Council))
	}
	return n
}

func (m *BoosterPack) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SetId != 0 {
		n += 1 + sovUser(uint64(m.SetId))
	}
	if m.TimeStamp != 0 {
		n += 1 + sovUser(uint64(m.TimeStamp))
	}
	if len(m.RaritiesPerPack) > 0 {
		l = 0
		for _, e := range m.RaritiesPerPack {
			l += sovUser(uint64(e))
		}
		n += 1 + sovUser(uint64(l)) + l
	}
	if len(m.DropRatiosPerPack) > 0 {
		l = 0
		for _, e := range m.DropRatiosPerPack {
			l += sovUser(uint64(e))
		}
		n += 1 + sovUser(uint64(l)) + l
	}
	return n
}

func (m *AirDrops) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Vote {
		n += 2
	}
	if m.Create {
		n += 2
	}
	if m.Buy {
		n += 2
	}
	if m.Play {
		n += 2
	}
	if m.User {
		n += 2
	}
	return n
}

func sovUser(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUser(x uint64) (n int) {
	return sovUser(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *User) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: User: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alias = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OwnedCardSchemes = append(m.OwnedCardSchemes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUser
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUser
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.OwnedCardSchemes) == 0 {
					m.OwnedCardSchemes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUser
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OwnedCardSchemes = append(m.OwnedCardSchemes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnedCardSchemes", wireType)
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.OwnedPrototypes = append(m.OwnedPrototypes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUser
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUser
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.OwnedPrototypes) == 0 {
					m.OwnedPrototypes = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUser
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.OwnedPrototypes = append(m.OwnedPrototypes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnedPrototypes", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Cards = append(m.Cards, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUser
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUser
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Cards) == 0 {
					m.Cards = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUser
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Cards = append(m.Cards, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Cards", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteRights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VoteRights = append(m.VoteRights, &VoteRight{})
			if err := m.VoteRights[len(m.VoteRights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CouncilParticipation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CouncilParticipation == nil {
				m.CouncilParticipation = &CouncilParticipation{}
			}
			if err := m.CouncilParticipation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportMatches", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReportMatches = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfileCard", wireType)
			}
			m.ProfileCard = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProfileCard |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirDrops", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AirDrops == nil {
				m.AirDrops = &AirDrops{}
			}
			if err := m.AirDrops.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoosterPacks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BoosterPacks = append(m.BoosterPacks, &BoosterPack{})
			if err := m.BoosterPacks[len(m.BoosterPacks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Website", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Website = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Biography", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Biography = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CouncilParticipation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CouncilParticipation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CouncilParticipation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= CouncilStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Council", wireType)
			}
			m.Council = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Council |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BoosterPack) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BoosterPack: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BoosterPack: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetId", wireType)
			}
			m.SetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStamp", wireType)
			}
			m.TimeStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeStamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.RaritiesPerPack = append(m.RaritiesPerPack, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUser
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUser
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.RaritiesPerPack) == 0 {
					m.RaritiesPerPack = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUser
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.RaritiesPerPack = append(m.RaritiesPerPack, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field RaritiesPerPack", wireType)
			}
		case 4:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.DropRatiosPerPack = append(m.DropRatiosPerPack, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUser
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUser
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUser
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.DropRatiosPerPack) == 0 {
					m.DropRatiosPerPack = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUser
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.DropRatiosPerPack = append(m.DropRatiosPerPack, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field DropRatiosPerPack", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AirDrops) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AirDrops: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AirDrops: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vote", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Vote = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Create", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Create = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buy", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Buy = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Play", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Play = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.User = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUser(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUser
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUser
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUser
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUser
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUser        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUser          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUser = fmt.Errorf("proto: unexpected end of group")
)
