"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Params = exports.ValidatorSigningInfo = exports.MissedBlock = exports.ValidatorMissedBlocks = exports.SigningInfo = void 0;
const genesis_1 = require("./types/cosmos/slashing/v1beta1/genesis");
Object.defineProperty(exports, "SigningInfo", { enumerable: true, get: function () { return genesis_1.SigningInfo; } });
const genesis_2 = require("./types/cosmos/slashing/v1beta1/genesis");
Object.defineProperty(exports, "ValidatorMissedBlocks", { enumerable: true, get: function () { return genesis_2.ValidatorMissedBlocks; } });
const genesis_3 = require("./types/cosmos/slashing/v1beta1/genesis");
Object.defineProperty(exports, "MissedBlock", { enumerable: true, get: function () { return genesis_3.MissedBlock; } });
const slashing_1 = require("./types/cosmos/slashing/v1beta1/slashing");
Object.defineProperty(exports, "ValidatorSigningInfo", { enumerable: true, get: function () { return slashing_1.ValidatorSigningInfo; } });
const slashing_2 = require("./types/cosmos/slashing/v1beta1/slashing");
Object.defineProperty(exports, "Params", { enumerable: true, get: function () { return slashing_2.Params; } });
