name: Test CD

on:
  push:
    branches:
      - development

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
      - name: install liefer
        run: |
          go install github.com/lxgr-linux/liefer@latest
      - name: deploy
        run: |
          ~/go/bin/liefer deliver devnet development ${{ secrets.LIEFER_PRIVKEY }} --address ${{ secrets.LXGR_HOST }}:8080